[workspace]
members = ["packages/*", "contracts/*"]

[workspace.package]
version       = "0.1.0-alpha.1"
edition       = "2021"
license       = "Apache-2.0"
repository    = "https://github.com/bitsongofficial/bs-nfts"
homepage      = "https://bitsong.io"
documentation = "https://docs.bitsong.io"

[workspace.dependencies]
cosmwasm-schema = "1.1.5"
cosmwasm-std    = "1.1.5"
cw2             = "0.16.0"
cw20            = "0.16.0"
bs721           = { version = "0.1.0-alpha.1", path = "./packages/bs721" }
bs721-base      = { version = "0.1.0-alpha.1", path = "./contracts/bs721-base" }
bs721-royalties   = { version = "0.1.0-alpha.1", path = "./contracts/bs721-royalties" }
cw-storage-plus = "0.16.0"
cw-utils        = "0.16.0"
schemars        = "0.8.10"
serde           = { version = "1.0.140", default-features = false, features = ["derive"] }
thiserror       = "1.0.31"

[profile.release.package.bs721-base]
codegen-units = 1
incremental = false

[profile.release.package.bs721-royalties]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
