[package]
name        = "bs-mint-hooks-derive"
version     = { workspace = true }
description = "Macros for generating code used by the `bs-mint-hooks` crate"
authors     = [
  "Shane Vitarana <s@users.noreply.publicawesome.com>",
  "A Hardnett <hard-nett@users.noreply.github.com>"
]
edition     = { workspace = true }
homepage    = { workspace = true }
repository  = { workspace = true }
license     = { workspace = true }

[lib]
doctest    = false # disable doc tests
proc-macro = true

[dependencies]
proc-macro2    = "1"
quote          = "1"
syn            = "1"
bs-controllers = { workspace = true }
